name: Flutter Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Folder
        run: flutter create --platforms=android --org=com.jm.alchemy .

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze || true

      - name: Build APK
        run: flutter build apk --release --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
